name: Update Custom_Clash_X.ini

on:
  push:
    paths:
      - cfg/Custom_Clash.ini
  workflow_dispatch:

jobs:
  update-Xfile:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate Custom_Clash_X.ini
      run: python py/generate_Xfile.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add cfg/Custom_Clash_X.ini

        # 确保在 main 分支
        git checkout main

        # 判断是否有变更，只有在有变更时才提交
        if ! git diff --cached --quiet; then
          git commit -m "Update Custom_Clash_X.ini based on Custom_Clash.ini"
          git pull --rebase origin main
          git push origin main
        else
          echo "No changes to commit."
        fi
